serversTransport:
  insecureSkipVerify: true # https://community.traefik.io/t/insecureskipverify-explanation/2195/2
log:
  level: DEBUG
api:
  dashboard: true
  debug: true
  insecure: false
ping:
  entryPoint: websecure
providers:
  docker:
    exposedByDefault: true
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
    # forwardedHeaders:
    #   insecure: true
  websecure:
    address: :443
    # forwardedHeaders:
    #   insecure: true

