api:
  dashboard: true
  debug: true
providers:
  docker:
    exposedByDefault: true
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
